// <auto-generated />
namespace Fl.Data.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExpandPasswordField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpandPasswordField));
        
        string IMigrationMetadata.Id
        {
            get { return "201512131336090_ExpandPasswordField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
